version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: improv-playground
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'  
  backend:
      build: .
      command: npm run dev:ts
      volumes:
        - .:/usr/app/
        - /usr/app/node_modules
      ports:
        - '4000:4000'
      depends_on:
        - db